/**
 * Displays the pollution generated by each power module. 
 * 
 * @author Brittany Pruneau 
 * 
 */

package finalProject;

public abstract interface Pollution
{
	void showAnnualPollutionFromElectricityUse(Environment env, Double yearlyElectricity);
	void showAnnualPollutionFromNaturalGasUsage(Environment env, Double yearlyElectricity);
	
	
}
